/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenBenchmarkRouteImport } from './routes/screen-benchmark'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ScreenPreviewIdRouteImport } from './routes/screen-preview.$id'
import { Route as ScreenEditorPreviewIdRouteImport } from './routes/screen-editor-preview.$id'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppMenusRouteImport } from './routes/_app.menus'
import { Route as AppDictRouteImport } from './routes/_app.dict'
import { Route as AppDatasourceConnectionRouteImport } from './routes/_app.datasource-connection'
import { Route as AppDataTablePlaygroundRouteImport } from './routes/_app.data-table-playground'
import { Route as AppScreenIndexRouteImport } from './routes/_app.screen.index'
import { Route as AppDatasetIndexRouteImport } from './routes/_app.dataset.index'
import { Route as AppScreenIdRouteImport } from './routes/_app.screen.$id'
import { Route as AppDatasetIdRouteImport } from './routes/_app.dataset.$id'

const ScreenBenchmarkRoute = ScreenBenchmarkRouteImport.update({
  id: '/screen-benchmark',
  path: '/screen-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ScreenPreviewIdRoute = ScreenPreviewIdRouteImport.update({
  id: '/screen-preview/$id',
  path: '/screen-preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenEditorPreviewIdRoute = ScreenEditorPreviewIdRouteImport.update({
  id: '/screen-editor-preview/$id',
  path: '/screen-editor-preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppDictRoute = AppDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasourceConnectionRoute = AppDatasourceConnectionRouteImport.update({
  id: '/datasource-connection',
  path: '/datasource-connection',
  getParentRoute: () => AppRoute,
} as any)
const AppDataTablePlaygroundRoute = AppDataTablePlaygroundRouteImport.update({
  id: '/data-table-playground',
  path: '/data-table-playground',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenIndexRoute = AppScreenIndexRouteImport.update({
  id: '/screen/',
  path: '/screen/',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetIndexRoute = AppDatasetIndexRouteImport.update({
  id: '/dataset/',
  path: '/dataset/',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenIdRoute = AppScreenIdRouteImport.update({
  id: '/screen/$id',
  path: '/screen/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetIdRoute = AppDatasetIdRouteImport.update({
  id: '/dataset/$id',
  path: '/dataset/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/screen-benchmark': typeof ScreenBenchmarkRoute
  '/data-table-playground': typeof AppDataTablePlaygroundRoute
  '/datasource-connection': typeof AppDatasourceConnectionRoute
  '/dict': typeof AppDictRoute
  '/menus': typeof AppMenusRoute
  '/roles': typeof AppRolesRoute
  '/users': typeof AppUsersRoute
  '/screen-editor-preview/$id': typeof ScreenEditorPreviewIdRoute
  '/screen-preview/$id': typeof ScreenPreviewIdRoute
  '/dataset/$id': typeof AppDatasetIdRoute
  '/screen/$id': typeof AppScreenIdRoute
  '/dataset/': typeof AppDatasetIndexRoute
  '/screen/': typeof AppScreenIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/screen-benchmark': typeof ScreenBenchmarkRoute
  '/data-table-playground': typeof AppDataTablePlaygroundRoute
  '/datasource-connection': typeof AppDatasourceConnectionRoute
  '/dict': typeof AppDictRoute
  '/menus': typeof AppMenusRoute
  '/roles': typeof AppRolesRoute
  '/users': typeof AppUsersRoute
  '/screen-editor-preview/$id': typeof ScreenEditorPreviewIdRoute
  '/screen-preview/$id': typeof ScreenPreviewIdRoute
  '/': typeof AppIndexRoute
  '/dataset/$id': typeof AppDatasetIdRoute
  '/screen/$id': typeof AppScreenIdRoute
  '/dataset': typeof AppDatasetIndexRoute
  '/screen': typeof AppScreenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/screen-benchmark': typeof ScreenBenchmarkRoute
  '/_app/data-table-playground': typeof AppDataTablePlaygroundRoute
  '/_app/datasource-connection': typeof AppDatasourceConnectionRoute
  '/_app/dict': typeof AppDictRoute
  '/_app/menus': typeof AppMenusRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/users': typeof AppUsersRoute
  '/screen-editor-preview/$id': typeof ScreenEditorPreviewIdRoute
  '/screen-preview/$id': typeof ScreenPreviewIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dataset/$id': typeof AppDatasetIdRoute
  '/_app/screen/$id': typeof AppScreenIdRoute
  '/_app/dataset/': typeof AppDatasetIndexRoute
  '/_app/screen/': typeof AppScreenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/screen-benchmark'
    | '/data-table-playground'
    | '/datasource-connection'
    | '/dict'
    | '/menus'
    | '/roles'
    | '/users'
    | '/screen-editor-preview/$id'
    | '/screen-preview/$id'
    | '/dataset/$id'
    | '/screen/$id'
    | '/dataset/'
    | '/screen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/screen-benchmark'
    | '/data-table-playground'
    | '/datasource-connection'
    | '/dict'
    | '/menus'
    | '/roles'
    | '/users'
    | '/screen-editor-preview/$id'
    | '/screen-preview/$id'
    | '/'
    | '/dataset/$id'
    | '/screen/$id'
    | '/dataset'
    | '/screen'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/screen-benchmark'
    | '/_app/data-table-playground'
    | '/_app/datasource-connection'
    | '/_app/dict'
    | '/_app/menus'
    | '/_app/roles'
    | '/_app/users'
    | '/screen-editor-preview/$id'
    | '/screen-preview/$id'
    | '/_app/'
    | '/_app/dataset/$id'
    | '/_app/screen/$id'
    | '/_app/dataset/'
    | '/_app/screen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ScreenBenchmarkRoute: typeof ScreenBenchmarkRoute
  ScreenEditorPreviewIdRoute: typeof ScreenEditorPreviewIdRoute
  ScreenPreviewIdRoute: typeof ScreenPreviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screen-benchmark': {
      id: '/screen-benchmark'
      path: '/screen-benchmark'
      fullPath: '/screen-benchmark'
      preLoaderRoute: typeof ScreenBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/screen-preview/$id': {
      id: '/screen-preview/$id'
      path: '/screen-preview/$id'
      fullPath: '/screen-preview/$id'
      preLoaderRoute: typeof ScreenPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-editor-preview/$id': {
      id: '/screen-editor-preview/$id'
      path: '/screen-editor-preview/$id'
      fullPath: '/screen-editor-preview/$id'
      preLoaderRoute: typeof ScreenEditorPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dict': {
      id: '/_app/dict'
      path: '/dict'
      fullPath: '/dict'
      preLoaderRoute: typeof AppDictRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/datasource-connection': {
      id: '/_app/datasource-connection'
      path: '/datasource-connection'
      fullPath: '/datasource-connection'
      preLoaderRoute: typeof AppDatasourceConnectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-table-playground': {
      id: '/_app/data-table-playground'
      path: '/data-table-playground'
      fullPath: '/data-table-playground'
      preLoaderRoute: typeof AppDataTablePlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screen/': {
      id: '/_app/screen/'
      path: '/screen'
      fullPath: '/screen/'
      preLoaderRoute: typeof AppScreenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dataset/': {
      id: '/_app/dataset/'
      path: '/dataset'
      fullPath: '/dataset/'
      preLoaderRoute: typeof AppDatasetIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screen/$id': {
      id: '/_app/screen/$id'
      path: '/screen/$id'
      fullPath: '/screen/$id'
      preLoaderRoute: typeof AppScreenIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dataset/$id': {
      id: '/_app/dataset/$id'
      path: '/dataset/$id'
      fullPath: '/dataset/$id'
      preLoaderRoute: typeof AppDatasetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDataTablePlaygroundRoute: typeof AppDataTablePlaygroundRoute
  AppDatasourceConnectionRoute: typeof AppDatasourceConnectionRoute
  AppDictRoute: typeof AppDictRoute
  AppMenusRoute: typeof AppMenusRoute
  AppRolesRoute: typeof AppRolesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDatasetIdRoute: typeof AppDatasetIdRoute
  AppScreenIdRoute: typeof AppScreenIdRoute
  AppDatasetIndexRoute: typeof AppDatasetIndexRoute
  AppScreenIndexRoute: typeof AppScreenIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDataTablePlaygroundRoute: AppDataTablePlaygroundRoute,
  AppDatasourceConnectionRoute: AppDatasourceConnectionRoute,
  AppDictRoute: AppDictRoute,
  AppMenusRoute: AppMenusRoute,
  AppRolesRoute: AppRolesRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDatasetIdRoute: AppDatasetIdRoute,
  AppScreenIdRoute: AppScreenIdRoute,
  AppDatasetIndexRoute: AppDatasetIndexRoute,
  AppScreenIndexRoute: AppScreenIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ScreenBenchmarkRoute: ScreenBenchmarkRoute,
  ScreenEditorPreviewIdRoute: ScreenEditorPreviewIdRoute,
  ScreenPreviewIdRoute: ScreenPreviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
