/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppMenusRouteImport } from './routes/_app.menus'
import { Route as AppDictRouteImport } from './routes/_app.dict'
import { Route as AppDataTablePlaygroundRouteImport } from './routes/_app.data-table-playground'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppMenusRoute = AppMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppDictRoute = AppDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AppRoute,
} as any)
const AppDataTablePlaygroundRoute = AppDataTablePlaygroundRouteImport.update({
  id: '/data-table-playground',
  path: '/data-table-playground',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/data-table-playground': typeof AppDataTablePlaygroundRoute
  '/dict': typeof AppDictRoute
  '/menus': typeof AppMenusRoute
  '/roles': typeof AppRolesRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/data-table-playground': typeof AppDataTablePlaygroundRoute
  '/dict': typeof AppDictRoute
  '/menus': typeof AppMenusRoute
  '/roles': typeof AppRolesRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/data-table-playground': typeof AppDataTablePlaygroundRoute
  '/_app/dict': typeof AppDictRoute
  '/_app/menus': typeof AppMenusRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/data-table-playground'
    | '/dict'
    | '/menus'
    | '/roles'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/data-table-playground'
    | '/dict'
    | '/menus'
    | '/roles'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/data-table-playground'
    | '/_app/dict'
    | '/_app/menus'
    | '/_app/roles'
    | '/_app/users'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menus': {
      id: '/_app/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof AppMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dict': {
      id: '/_app/dict'
      path: '/dict'
      fullPath: '/dict'
      preLoaderRoute: typeof AppDictRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-table-playground': {
      id: '/_app/data-table-playground'
      path: '/data-table-playground'
      fullPath: '/data-table-playground'
      preLoaderRoute: typeof AppDataTablePlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDataTablePlaygroundRoute: typeof AppDataTablePlaygroundRoute
  AppDictRoute: typeof AppDictRoute
  AppMenusRoute: typeof AppMenusRoute
  AppRolesRoute: typeof AppRolesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDataTablePlaygroundRoute: AppDataTablePlaygroundRoute,
  AppDictRoute: AppDictRoute,
  AppMenusRoute: AppMenusRoute,
  AppRolesRoute: AppRolesRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
