import { z } from 'zod';
import type { EndpointContract } from './dataset.contract.js';
import {
  CreateScreenProjectSchema,
  ExecuteScreenHostResourceSchema,
  ListScreenHostResourcesQuerySchema,
  PublishScreenProjectSchema,
  ScreenHostResourceResponseSchema,
  ScreenHostResourceSummarySchema,
  ScreenProjectSchema,
  UpdateScreenProjectSchema,
} from '../schemas/screen.schema.js';

export const SCREEN_CONTRACT = {
  phase: 1 as const,
  endpoints: {
    create: {
      method: 'POST',
      path: '/screen',
      phase: 1,
      description: '创建大屏项目',
      body: CreateScreenProjectSchema,
      response: ScreenProjectSchema,
    } as const satisfies EndpointContract,
    list: {
      method: 'GET',
      path: '/screen',
      phase: 1,
      description: '获取大屏项目列表',
      response: z.array(ScreenProjectSchema),
    } as const satisfies EndpointContract,
    getOne: {
      method: 'GET',
      path: '/screen/:projectId',
      phase: 1,
      description: '获取大屏项目',
      pathParams: ['projectId'],
      response: ScreenProjectSchema,
    } as const satisfies EndpointContract,
    update: {
      method: 'PATCH',
      path: '/screen/:projectId',
      phase: 1,
      description: '更新项目元数据或原子替换完整文档',
      pathParams: ['projectId'],
      body: UpdateScreenProjectSchema,
      response: ScreenProjectSchema,
    } as const satisfies EndpointContract,
    publish: {
      method: 'POST',
      path: '/screen/:projectId/publish',
      phase: 1,
      description: '发布大屏项目',
      pathParams: ['projectId'],
      body: PublishScreenProjectSchema,
      response: ScreenProjectSchema,
    } as const satisfies EndpointContract,
    remove: {
      method: 'DELETE',
      path: '/screen/:projectId',
      phase: 1,
      description: '删除大屏项目',
      pathParams: ['projectId'],
      response: undefined,
    } as const satisfies EndpointContract,
    preview: {
      method: 'GET',
      path: '/screen/:projectId/preview',
      phase: 1,
      description: '获取已发布项目的公开预览',
      pathParams: ['projectId'],
      response: ScreenProjectSchema,
    } as const satisfies EndpointContract,
    listResources: {
      method: 'GET',
      path: '/screen/:projectId/resources',
      phase: 1,
      description: '列出已认证项目可用的宿主资源',
      pathParams: ['projectId'],
      query: ListScreenHostResourcesQuerySchema,
      response: z.array(ScreenHostResourceSummarySchema),
    } as const satisfies EndpointContract,
    executeResource: {
      method: 'POST',
      path: '/screen/:projectId/resources/execute',
      phase: 1,
      description: '执行已认证项目的宿主资源',
      pathParams: ['projectId'],
      body: ExecuteScreenHostResourceSchema,
      response: ScreenHostResourceResponseSchema,
    } as const satisfies EndpointContract,
    executePreviewResource: {
      method: 'POST',
      path: '/screen/:projectId/preview/resources/execute',
      phase: 1,
      description: '执行已发布项目的公开预览宿主资源',
      pathParams: ['projectId'],
      body: ExecuteScreenHostResourceSchema,
      response: ScreenHostResourceResponseSchema,
    } as const satisfies EndpointContract,
  },
} as const;
